![NumPy image](images/NumPy_logo.svg.png)

# NumPy(넘파이)

### <span style="color:red">NumPy는 행렬이나 대규모 다차원 배열을 쉽게 처리 할 수 있도록 지원하는 파이썬의 라이브러리</span>입니다. 
### NumPy는 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공합니다.
### 다차원 행렬 자료구조인 ndarray 객체를 핵심으로 선형대수 연산이 필요한 함수들을 제공합니다.
----
### Python List
* 여러가지 타입의 원소
* linked List 구현
* 메모리 용량이 크고 속도가 느림
* 벡터화 연산 불가

### NumPy ndarray
* 동일 타입의 원소
* contiguous memory layout
* 메모리 최적화, 계산 속도 향상
* 벡터화 연산 가능

In [1]:
import numpy as np

In [3]:
# 행으로 구성된 벡터 - 1차원 ndarray 객체 
vector_row = np.array([1, 2, 3])
print(vector_row)
print(type(vector_row))
print(vector_row.ndim)
print(vector_row.size)

[1 2 3]
<class 'numpy.ndarray'>
1
3


In [4]:
# 열로 구성된 벡터 - 2차원 ndarray 객체 
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)
print(type(vector_column))
print(vector_column.ndim)
print(vector_column.size)

[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>
2
3


In [8]:
a1 = np.arange(30)
print(a1)
print(type(a1))
print(a1.ndim)
print(a1.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>
1
30


In [7]:
a2 = np.arange(1, 31)
print(a2)
print(type(a2))
print(a2.ndim)
print(a2.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
<class 'numpy.ndarray'>
1
30


In [6]:
a3 = np.arange(5, 30)
print(a3)
print(type(a3))
print(a3.ndim)
print(a3.size)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29]
<class 'numpy.ndarray'>
1
25


In [5]:
a4 = np.arange(5, 30, 3)
print(a4)
print(type(a4))
print(a4.ndim)
print(a4.size)

[ 5  8 11 14 17 20 23 26 29]
<class 'numpy.ndarray'>
1
9


In [ ]:
np.arange(0, 5, 0.5)

In [ ]:
np.arange(0, 5, -0.5) # empty

In [ ]:
np.arange(5, 0, -0.5)

In [9]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
print(matrix)
print(type(matrix))
print(matrix.ndim)

[[1 2]
 [1 2]
 [1 2]]
<class 'numpy.ndarray'>
2


In [10]:
matrix2 = np.mat([[1, 2],
                  [1, 2],
                  [1, 2]])
print(matrix2)
print(type(matrix2))
print(matrix2.ndim)

[[1 2]
 [1 2]
 [1 2]]
<class 'numpy.matrix'>
2


In [11]:
empty_matrix = np.empty((3, 2))
print(empty_matrix)
print(type(empty_matrix))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [13]:
zero_matrix = np.zeros((3, 2))
print(zero_matrix)
print(type(zero_matrix))
print(zero_matrix.ndim)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>
2


In [14]:
one_matrix = np.ones((3, 2))
print(one_matrix)
print(type(one_matrix))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [15]:
copy_matrix = np.array(one_matrix) # 복제
print(one_matrix)
print(copy_matrix)
print(copy_matrix is one_matrix)
copy_matrix[0,0] = 100
print(one_matrix)
print(copy_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
False
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[100.   1.]
 [  1.   1.]
 [  1.   1.]]


In [16]:
ref_matrix = np.asarray(one_matrix) # 참조
print(one_matrix)
print(ref_matrix)
print(ref_matrix is one_matrix)
ref_matrix[0,0] = 100
print(one_matrix)
print(ref_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
True
[[100.   1.]
 [  1.   1.]
 [  1.   1.]]
[[100.   1.]
 [  1.   1.]
 [  1.   1.]]


In [17]:
x = np.array([0,1,2])
print(x + 5)

[5 6 7]


In [18]:
A = np.ones([3,3])
print(A)
print(x)
print(A + x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


<img src='images/numpy1.png' width=500 height=400>

In [19]:
vector = np.array([10, 20, 30, 40, 50, 60]) 

In [20]:
print(type(vector))

<class 'numpy.ndarray'>


In [21]:
vector[0]

10

In [22]:
vector[2]

30

In [23]:
vector[:]

array([10, 20, 30, 40, 50, 60])

In [24]:
vector[:3]

array([10, 20, 30])

In [25]:
vector[3:]

array([40, 50, 60])

In [26]:
vector[-1]

60

In [27]:
vector[-4:-1]

array([30, 40, 50])

In [30]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [29]:
matrix[0,0]

1

In [31]:
matrix[1,1]

5

In [32]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [34]:
matrix[0]

array([1, 2, 3])

In [ ]:
matrix[2]

In [ ]:
# 첫 번째 행과 세 번째 행을 선택
matrix[[0,2]]

In [35]:
matrix[[0,2], [1,0]]

array([2, 7])

In [36]:
mask = matrix > 5

mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [37]:
matrix[mask]  

array([6, 7, 8, 9])

In [38]:
matrix[matrix > 5] 

array([6, 7, 8, 9])

In [39]:
select_element = matrix[matrix > 5] 
select_element[0] = 100
print(select_element)
print(matrix)

[100   7   8   9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### reshape은 데이터 변경없이 지정된 shape으로 변환하는 메서드

In [40]:
m1 = matrix[mask]
m2 = m1.reshape(2,2)
print(m1)
print("reshape 후----")
print(m2)

[6 7 8 9]
reshape 후----
[[6 7]
 [8 9]]


In [41]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# 행렬의 크기
matrix.shape

(3, 4)

In [42]:
# 행렬의 원소 개수
matrix.size

12

In [43]:
# 차원 수
matrix.ndim

2

In [44]:
matrix.dtype

dtype('int32')

In [45]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.max(matrix)

9

In [46]:
np.min(matrix)

1

In [48]:
print(matrix)
# axis가 0 이면 열단위로 최대값
print(np.max(matrix, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [47]:
print(matrix)
# axis가 1 이면 행단위로 최대값
print(np.max(matrix, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


In [ ]:
print(matrix)
print(matrix + 100)

In [49]:
add100 = lambda i: i + 100 if i % 2 == 1 else i

# 함수 호출을 통해서 배열의 값을 제구성 함
vectorized_add100 = np.vectorize(add100)

# 행렬의 모든 원소에 함수를 적용합니다.
print(vectorized_add100(matrix))

[[101   2 103]
 [  4 105   6]
 [107   8 109]]


In [50]:
vector_column = np.max(matrix, axis=1, keepdims=True) #행렬형태 유지 

In [53]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
vector_column

array([[3],
       [6],
       [9]])

In [54]:
matrix - vector_column

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [55]:
np.mean(matrix)

5.0

In [56]:
# 분산
np.var(matrix)

6.666666666666667

In [57]:
# 표준 편차
np.std(matrix)

2.581988897471611

In [58]:
# 각 열의 평균
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [ ]:
# 각 행의 평균
np.mean(matrix, axis=1)

In [59]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

print(matrix)

# 2x6 행렬로 크기로 변경
matrix1 = matrix.reshape(2, 6)
print(matrix1)
matrix[0,0] = 100
print("---------------------------")
print(matrix)
print(matrix1)
print(matrix.shape)
print(matrix1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
---------------------------
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
[[100   2   3   4   5   6]
 [  7   8   9  10  11  12]]
(4, 3)
(2, 6)


<img src='images/numpy2.png' width=300 height=300>

In [60]:
matrix.T

array([[100,   4,   7,  10],
       [  2,   5,   8,  11],
       [  3,   6,   9,  12]])

In [61]:
matrix.transpose()

array([[100,   4,   7,  10],
       [  2,   5,   8,  11],
       [  3,   6,   9,  12]])

In [62]:
m1 = np.array([[1, 2],
               [4, 5]])

m2 = np.array([[10, 100],
               [10, 100]])

In [63]:
m1 + m2

array([[ 11, 102],
       [ 14, 105]])

In [64]:
np.add(m1, m2)

array([[ 11, 102],
       [ 14, 105]])

In [65]:
m1 - m2

array([[ -9, -98],
       [ -6, -95]])

In [66]:
np.subtract(m1, m2)

array([[ -9, -98],
       [ -6, -95]])

In [67]:
m1 * m2

array([[ 10, 200],
       [ 40, 500]])

In [68]:
np.dot(m1, m2) #곱셈

array([[ 30, 300],
       [ 90, 900]])

In [69]:
m1 @ m2

array([[ 30, 300],
       [ 90, 900]])

In [70]:
from PIL import Image    
r2d2 = np.array(Image.open('data/r2d2.JPG')) 

In [71]:
r2d2

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [72]:
# 초깃값 지정
np.random.seed(0)

In [73]:
# 0.0과 1.0 사이에서 세 개의 실수 난수
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [74]:
# 0.0과 1.0 사이에서 열개의 실수 난수
np.random.random(10)

array([0.54488318, 0.4236548 , 0.64589411, 0.43758721, 0.891773  ,
       0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456])

In [75]:
# 0.0과 1.0 사이에서 열개의 실수 난수
np.random.rand(10)

array([0.92559664, 0.07103606, 0.0871293 , 0.0202184 , 0.83261985,
       0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936])

In [76]:
# 0.0과 1.0 사이에서 5행 2열 구조의 실수 난수
np.random.rand(5,2) # 2차원으로도 추출 가능

array([[0.78052918, 0.11827443],
       [0.63992102, 0.14335329],
       [0.94466892, 0.52184832],
       [0.41466194, 0.26455561],
       [0.77423369, 0.45615033]])

In [77]:
# 0과 10 사이에서 세 개의 정수 난수
np.random.randint(0, 11, 3)

array([2, 0, 0])

In [78]:
# 0과 10 사이에서 세 개의 정수 난수
np.random.randint(0, 11, 8)

array([4, 5, 5, 6, 8, 4, 1, 4])

In [79]:
a = np.random.randint(1, 10, (2, 6))
print(a)

[[9 2 2 8 4 7]
 [8 3 1 4 6 5]]


In [80]:
# 평균이 0.0이고 표준 편차가 1.0인 정규 분포에서 세 개의 수
np.random.normal(0.0, 1.0, 3)

array([0.40539778, 0.11860659, 1.25441407])

In [81]:
np.random.choice([0,1,2], 5)

array([0, 0, 0, 0, 2])

In [84]:
a = np.array([0, 1, 2, 3, 4])
np.random.shuffle(a)
print(a)

[2 4 1 0 3]
